# Generated by Django 2.2.4 on 2019-10-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webstatus',
            name='verbose_status',
            field=models.CharField(default='Bunga Bunga', max_length=50, verbose_name='Descrption'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webstatus',
            name='status',
            field=models.IntegerField(verbose_name='HTTP Status'),
        ),
    ]
