# Generated by Django 2.2.4 on 2019-10-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping_app', '0002_auto_20191002_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='webstatus',
            name='request_type',
            field=models.CharField(choices=[('GET', '1'), ('HEAD', '2'), ('POST', '3'), ('PUT', '4'), ('DELETE', '5'), ('OPTIONS', '6')], default='7', max_length=1),
        ),
    ]
