# Generated by Django 2.2.4 on 2019-10-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping_app', '0003_webstatus_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webstatus',
            name='request_type',
            field=models.CharField(choices=[('1', 'GET'), ('2', 'HEAD'), ('3', 'POST'), ('4', 'PUT'), ('5', 'DELETE'), ('6', 'OPTIONS')], default='7', max_length=1),
        ),
    ]
