# Generated by Django 2.2.4 on 2019-10-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping_app', '0004_auto_20191002_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webstatus',
            name='request_type',
            field=models.CharField(choices=[('1', 'GET'), ('2', 'HEAD'), ('3', 'OPTIONS')], max_length=1),
        ),
    ]
