# Generated by Django 2.2.4 on 2019-10-07 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='organization',
        ),
        migrations.AddField(
            model_name='projects',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='team.Team'),
            preserve_default=False,
        ),
    ]
