# Generated by Django 2.2.4 on 2019-10-07 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=12, unique=True)),
                ('team_name', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('team_admins', models.ManyToManyField(related_name='team_admins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Organization',
            },
        ),
    ]
