# Generated by Django 2.2.4 on 2019-09-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_manager', '0002_auto_20190924_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttoken',
            name='refresh_token',
        ),
    ]
