# Generated by Django 2.2 on 2019-04-30 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('_id', models.UUIDField(default=uuid.UUID('44d5bb55-eda2-4586-9745-bee91e1714ad'), primary_key=True, serialize=False)),
                ('error_name', models.CharField(max_length=50)),
                ('error_description', models.TextField(max_length=500)),
                ('point_of_origin', models.CharField(default=None, max_length=30, null=True)),
                ('logged_at', models.DateTimeField(default=datetime.datetime(2019, 4, 30, 9, 13, 14, 803501, tzinfo=utc))),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(default=None)),
                ('warning_level', models.IntegerField(blank=True, default=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('_id', models.UUIDField(default=uuid.UUID('44044c9f-8e32-4ed8-ae42-ea3a1dcbd446'), primary_key=True, serialize=False)),
                ('logs', models.TextField(max_length=1000)),
                ('logged_at', models.DateTimeField(default=datetime.datetime(2019, 4, 30, 9, 13, 14, 803876, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 4, 30, 9, 13, 14, 803021, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 4, 30, 9, 13, 14, 803046, tzinfo=utc))),
                ('is_admin', models.BooleanField(default=False)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_mobile', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
