# Generated by Django 2.2 on 2019-05-06 07:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0002_auto_20190430_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errors',
            options={'get_latest_by': ['-logged_at'], 'ordering': ['-logged_at']},
        ),
        migrations.AddField(
            model_name='errors',
            name='resolved_by',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='bugtracker.User'),
        ),
        migrations.AddField(
            model_name='logs',
            name='log_title',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='errors',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('3040dfbf-e662-4891-9921-6f40936ee141'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errors',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 7, 57, 49, 519274, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logs',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('d219497e-d5df-4893-a3d9-6677bf2cad76'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 7, 57, 49, 520305, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 7, 57, 49, 518294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 7, 57, 49, 518319, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('_id', models.UUIDField(default=uuid.UUID('ff1ec116-4550-4d30-835d-00133c582aef'), primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(unique=True)),
                ('project_name', models.CharField(max_length=30)),
                ('project_description', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('registered_at', models.DateTimeField(default=datetime.datetime(2019, 5, 6, 7, 57, 49, 518827, tzinfo=utc))),
                ('updated_at', models.DateTimeField(blank=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugtracker.User')),
            ],
        ),
        migrations.AddField(
            model_name='errors',
            name='reference_project',
            field=models.ManyToManyField(blank=True, default=None, to='bugtracker.Projects'),
        ),
        migrations.AddField(
            model_name='logs',
            name='reference_project',
            field=models.ManyToManyField(blank=True, default=None, to='bugtracker.Projects'),
        ),
    ]
