# Generated by Django 2.2.4 on 2019-09-14 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0003_auto_20190913_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name_plural': 'Organisation'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name_plural': 'All Project name'},
        ),
        migrations.AlterModelOptions(
            name='projecttoken',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name_plural': 'Project Access Token'},
        ),
        migrations.AlterModelOptions(
            name='projectupdate',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name_plural': 'Project & User connecting Table'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'get_latest_by': ['created_at'], 'verbose_name_plural': 'User'},
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 15, 30, 11, 376495, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('61ac690b-365c-4b2d-bcb1-cc5b3c1fe7a3'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='979fcf9a-924', max_length=12, unique=True),
        ),
    ]
