# Generated by Django 2.2.4 on 2019-09-14 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0004_auto_20190914_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttoken',
            options={'verbose_name_plural': 'Project Access Token'},
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 15, 49, 9, 301624, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('4fca50fc-4e22-4a05-b6d7-6f6b921a54c1'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='515941cd-aa2', max_length=12, unique=True),
        ),
    ]
