# Generated by Django 2.2 on 2019-05-06 08:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0007_auto_20190506_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errors',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('658be2e6-57bf-4c59-ae01-002d4b9d0aa6'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errors',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 8, 41, 33, 759697, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='errors',
            name='resolved_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('d1fcdaf7-14e5-4ca7-b29c-004e92301a6e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 8, 41, 33, 760714, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('2ae9fdbe-26f0-4a29-8e11-74aaad512854'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.UUIDField(default=uuid.UUID('36028f3c-017a-416c-b4bc-4665e6cd4b66'), unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 8, 41, 33, 759276, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 8, 41, 33, 758687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 8, 41, 33, 758712, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('770010cb-2553-4d77-b757-2e5bb8074faa'), primary_key=True, serialize=False, unique=True),
        ),
    ]
