# Generated by Django 2.2 on 2019-05-06 08:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0010_auto_20190506_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errors',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('c9ec1c76-d2b2-4624-b2ec-cedfffe19d3e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errors',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 8, 59, 52, 847822, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logs',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('e122c8fb-b677-46a4-b0d1-3cc44ef78b71'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 8, 59, 52, 848917, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('7701ca1f-14ef-49d7-a636-46575ed93725'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.UUIDField(default=uuid.UUID('cc948c4b-d202-4a7a-b548-815deb1b29ae'), unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 8, 59, 52, 846988, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 8, 59, 52, 846451, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 8, 59, 52, 846492, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('759757a7-97cc-4774-81f0-f544dd5c516a'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='ProjectToken',
            fields=[
                ('_id', models.UUIDField(default=uuid.UUID('00c4aa65-9a61-4075-8b92-7dd35f7aecde'), primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.UUID('6171a392-42cc-4747-8891-1953165bc9e4'), unique=True)),
                ('refresh_token', models.UUIDField(default=uuid.UUID('8c831936-f77e-46d2-9210-9ecbcd103c69'), unique=True)),
                ('generated_at', models.DateTimeField(default=datetime.datetime(2019, 5, 6, 8, 59, 52, 847438, tzinfo=utc))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugtracker.Projects')),
            ],
        ),
    ]
