# Generated by Django 2.2 on 2019-05-08 09:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0019_auto_20190508_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errors',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('042a1a22-2495-40b2-91e3-72def7f71553'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errors',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 9, 45, 3, 924897, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logs',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('07484f9e-9ac2-4293-a0d7-b1cd6ad9d9bb'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 9, 45, 3, 925592, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('86aca3de-667d-40ae-8ab5-6318ba769819'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.UUIDField(default=uuid.UUID('fe309a84-f348-4e24-adbc-bf639ed9432f'), unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 9, 45, 3, 923854, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('ca81fbc2-4c1b-4755-9d87-f17e1e2f1b97'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='generated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 9, 45, 3, 924436, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='refresh_token',
            field=models.UUIDField(default=uuid.UUID('b1cbe6e7-432a-4df9-bf63-b1705e1a6aac'), unique=True),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('04984116-8d23-4df8-b5e6-9d1933c2c7e7'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 9, 45, 3, 922398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 9, 45, 3, 922431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('0ea2e638-7161-454a-b7c7-c315f761060b'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('_id', models.UUIDField(default=uuid.UUID('9f0af297-2de8-4deb-8ca0-7ba4aa8ccce6'), primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.UUID('d9363d82-b4ec-4be7-adb1-a03ef17e8136'), unique=True)),
                ('refresh_token', models.UUIDField(default=uuid.UUID('64d1e13e-f050-47ec-b754-e11e4229a442'), unique=True)),
                ('generated_at', models.DateTimeField(default=datetime.datetime(2019, 5, 8, 9, 45, 3, 923131, tzinfo=utc))),
                ('time_to_live', models.IntegerField(default=864000)),
                ('authorized_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugtracker.User')),
            ],
        ),
    ]
