# Generated by Django 2.2 on 2019-05-09 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0021_auto_20190509_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errors',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('7ce19b35-7a23-47d8-b0d6-f6c49445a1f5'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errors',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 9, 11, 21, 53, 218122, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logs',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('831fbfa4-0fc5-47b9-a10c-43a990dc98e8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 9, 11, 21, 53, 218712, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('6bcbf4c3-4af1-4152-bcb5-b6ed163c2d88'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.UUIDField(default=uuid.UUID('cec876ab-681c-4456-942f-983768db098a'), unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 9, 11, 21, 53, 217256, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('432ed729-7dee-4137-bd68-49bb42002093'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='generated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 9, 11, 21, 53, 217712, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='refresh_token',
            field=models.UUIDField(default=uuid.UUID('da0a7712-6861-4afe-9ae7-07e66255a3c0'), unique=True),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('2980e806-5ce6-4f60-b866-85168089236e'), unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('873a1c38-7b9f-4033-92f0-cc1224235e01'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='generated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 9, 11, 21, 53, 216794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='refresh_token',
            field=models.UUIDField(default=uuid.UUID('b79c78dd-9fce-459f-a65e-ee0877f1660a'), unique=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('6718607c-43f8-4370-b36c-d6b823fd77e1'), unique=True),
        ),
    ]
