# Generated by Django 2.2 on 2019-05-14 06:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0032_auto_20190514_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errors',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='errors',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='errors',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='errors',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('22167a0d-5712-42d8-b093-42987bf8f0b8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errors',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 6, 25, 44, 665043, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logs',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('80b661f4-9492-46c7-a67b-b19367d5f203'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 6, 25, 44, 666020, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('ef2fa3c5-40cf-448a-bd70-6b398994e26b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.UUIDField(default=uuid.UUID('9bb11bfe-77ce-429f-a264-7f4f40562d12'), unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 6, 25, 44, 663779, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('5848c887-b59c-4a71-a969-6163c281f3e6'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='generated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 6, 25, 44, 664639, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='refresh_token',
            field=models.UUIDField(default=uuid.UUID('8afdd92e-191c-4ee9-b57c-1ac412352894'), unique=True),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('a987d083-0ee6-4667-9953-39d9fff1dbde'), unique=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('c0fe4b1f-97fd-40e8-9984-26678f570556'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='generated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 6, 25, 44, 662583, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='refresh_token',
            field=models.UUIDField(default=uuid.UUID('6353ff43-9169-45c8-964b-8a3e8360e6cd'), unique=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('2ad9905d-ad7d-4cad-bf58-e8f3a4f50e63'), unique=True),
        ),
        migrations.CreateModel(
            name='ErrorStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_at', models.DateTimeField(default=datetime.datetime(2019, 5, 14, 6, 25, 44, 665511, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 5, 14, 6, 25, 44, 665531, tzinfo=utc))),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugtracker.Errors')),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugtracker.User')),
            ],
        ),
    ]
