# Generated by Django 2.2 on 2019-05-14 06:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0033_auto_20190514_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='errors',
            name='issued_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='bugtracker.User'),
        ),
        migrations.AlterField(
            model_name='errors',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('864a13a4-d150-447e-8caf-8c8fd7d04b3f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errors',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 6, 26, 10, 531847, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='errorstatus',
            name='resolved_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 6, 26, 10, 532386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='errorstatus',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 6, 26, 10, 532406, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logs',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('02cedc7b-9a74-4442-b7e7-8388b0a8ff4d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 6, 26, 10, 532920, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('f7b384a2-9582-45c1-87d2-261bd7ad9deb'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.UUIDField(default=uuid.UUID('286c8985-baf9-4946-9be4-574ed67a7804'), unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 6, 26, 10, 530597, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('053bb9e7-29c0-4649-901e-723ced983072'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='generated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 6, 26, 10, 531438, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='refresh_token',
            field=models.UUIDField(default=uuid.UUID('a8441756-5435-475f-9e47-9ace1960bcd2'), unique=True),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('699f75da-f1f8-4697-835d-c2c9468493ed'), unique=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('256211a4-cccc-4747-9e97-250abc64864c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='generated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 6, 26, 10, 529402, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='refresh_token',
            field=models.UUIDField(default=uuid.UUID('170d9d8e-d681-4314-9e13-01531bbe63b1'), unique=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('44385386-ad8c-47ee-afac-3dc352007c18'), unique=True),
        ),
    ]
