# Generated by Django 2.2 on 2019-05-14 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0035_auto_20190514_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errors',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('a188d924-7e53-4b6f-99ea-0801807ca1fd'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errors',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 11, 6, 597022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='errorstatus',
            name='resolved_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 11, 6, 597535, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='errorstatus',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 11, 6, 597556, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logs',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('c5abd284-0008-4ad3-a6b2-621c3de00d4f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 11, 6, 598054, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('e5fe2e66-ea55-4478-99bd-4a341cfe4cdd'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.UUIDField(default=uuid.UUID('6bc8da4c-af23-4912-b7d0-b4f9d22fad14'), unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 11, 6, 595720, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('a24315fd-3b71-492b-acda-db062dea8548'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='generated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 11, 6, 596604, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='refresh_token',
            field=models.UUIDField(default=uuid.UUID('e06106de-113c-4faf-adb3-30ad21db96b8'), unique=True),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('78dc2881-763d-455e-8ea9-f4919481f86d'), unique=True),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 11, 6, 596133, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('7eff6a47-9230-4495-a1d3-49636158cfe2'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='generated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='refresh_token',
            field=models.UUIDField(default=uuid.UUID('cae0ba18-976f-4837-9809-d9f4ec9e9d1f'), unique=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('e17906a6-589c-4d9c-b8b4-4892bbd0f7d1'), unique=True),
        ),
    ]
