# Generated by Django 2.2 on 2019-05-14 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0036_auto_20190514_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errors',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('33a0dd4f-34e2-402a-a6f3-b34ee8ea061b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errors',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 15, 31, 867634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='errorstatus',
            name='resolved_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 15, 31, 868352, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='errorstatus',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 15, 31, 868380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logs',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('207bead1-b989-4fdd-9d39-b5d2fdd22321'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 15, 31, 869093, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('22c14fee-a5d7-4fb0-bdbf-c1b65160d1ad'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.UUIDField(default=uuid.UUID('8da48885-a4cf-41e8-a702-f4cd03f39e66'), unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 15, 31, 865843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('7d82a1ba-f5e7-4f90-86f0-a6d4bf0d8d5d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='generated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 15, 31, 867051, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='refresh_token',
            field=models.UUIDField(default=uuid.UUID('9d83aa16-0a62-40e6-8c22-3eae4abba9f4'), unique=True),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('6cb12368-b241-4946-b220-2874bb30a66d'), unique=True),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 15, 31, 866418, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('a57d694c-4ddb-42b6-9e94-9dd8b0eb0c1c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='generated_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='refresh_token',
            field=models.UUIDField(default=uuid.UUID('40510eba-4312-4c4d-9b72-7f56e76e5237'), unique=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('98c1f311-282a-4422-96c3-d65eb512a52f'), unique=True),
        ),
    ]
