# Generated by Django 2.2 on 2019-05-14 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0037_auto_20190514_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errors',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('03b6c0b4-4071-474a-bd7d-b9ee22ca393a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errors',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 20, 39, 992065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='errorstatus',
            name='resolved_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 20, 39, 992603, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='errorstatus',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 20, 39, 992623, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logs',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('681bb4ec-142b-4d06-bde1-f99cd59cb0e7'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='logged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 20, 39, 993135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('eae67847-02e1-46f1-ae47-d4e9477a7bd6'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.UUIDField(default=uuid.UUID('2e97c37a-1c73-4697-8548-9ac80fbb9448'), unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 20, 39, 990714, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='_id',
            field=models.UUIDField(default=uuid.UUID('19712d9e-33f4-4b6f-ba9e-954912b22b24'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='generated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 20, 39, 991638, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='refresh_token',
            field=models.UUIDField(default=uuid.UUID('6bbf29c7-c282-45aa-bc49-3686f4f2cc3c'), unique=True),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='token',
            field=models.UUIDField(default=uuid.UUID('a915e25c-3cd2-4d4a-99b3-bd404b876424'), unique=True),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 20, 39, 991170, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='_id',
            field=models.UUIDField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='refresh_token',
            field=models.UUIDField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.UUIDField(blank=True, unique=True),
        ),
    ]
