# Generated by Django 2.2 on 2019-05-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0038_auto_20190514_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errors',
            name='_id',
            field=models.UUIDField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errors',
            name='logged_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='errorstatus',
            name='resolved_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='errorstatus',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='_id',
            field=models.UUIDField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='logged_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='_id',
            field=models.UUIDField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.UUIDField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='registered_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='_id',
            field=models.UUIDField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='generated_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='refresh_token',
            field=models.UUIDField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projecttoken',
            name='token',
            field=models.UUIDField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
