# Generated by Django 2.2 on 2019-05-15 08:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0039_auto_20190514_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='errors',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 15, 8, 7, 29, 215730, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logs',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 15, 8, 7, 34, 390521, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttoken',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 15, 8, 7, 38, 246183, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertoken',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 15, 8, 7, 42, 495655, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
