# Generated by Django 2.2 on 2019-05-22 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0041_usertoken_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('org_id', models.UUIDField(unique=True)),
                ('org_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugtracker.User')),
            ],
            options={
                'verbose_name_plural': 'Organisation',
            },
        ),
        migrations.CreateModel(
            name='UserToOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_added', models.DateTimeField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugtracker.Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugtracker.User')),
            ],
            options={
                'verbose_name_plural': 'UserToOrg',
            },
        ),
    ]
