# Generated by Django 2.2 on 2019-05-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0043_auto_20190522_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='_id',
            field=models.UUIDField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_id',
            field=models.UUIDField(blank=True, unique=True),
        ),
    ]
