# Generated by Django 2.2 on 2019-05-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0044_auto_20190522_0740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errors',
            options={'ordering': ['logged_at'], 'verbose_name_plural': 'All Error logs'},
        ),
        migrations.AlterModelOptions(
            name='errorstatus',
            options={'verbose_name_plural': 'Error User connecting Table'},
        ),
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name_plural': 'All debug logs'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'All Project name'},
        ),
        migrations.AlterModelOptions(
            name='projecttoken',
            options={'verbose_name_plural': 'Project Access Token'},
        ),
        migrations.AlterModelOptions(
            name='projectupdate',
            options={'verbose_name_plural': 'Project & User connecting Table'},
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name_plural': 'User Access Token management'},
        ),
        migrations.AlterModelOptions(
            name='usertoorg',
            options={'verbose_name_plural': 'User & Org connecting Table'},
        ),
        migrations.AddField(
            model_name='projects',
            name='organization',
            field=models.ForeignKey(default='cc1a5f68-7c9d-4984-a112-94bc25d8d083', on_delete=django.db.models.deletion.PROTECT, to='bugtracker.Organisation'),
            preserve_default=False,
        ),
    ]
