# Generated by Django 2.2 on 2019-06-03 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0046_auto_20190529_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('invited_at', models.DateTimeField(blank=True)),
                ('is_used', models.BooleanField(blank=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bugtracker.User')),
            ],
            options={
                'verbose_name_plural': 'Invitation',
            },
        ),
    ]
