BBBBBBB BBBBBBBBBBBBB
BBBBB BBBBB  BBBBBBBB

BBBBB BBBBBBB
XXXX XXX XXXXXXXXXX XXXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXX X XXXXXXXXXXXXXXXXXXXXX
    XXXXXXX X XXXXXXXXXXXXXXXXXX
    XX XXXX XX XXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
    X
XXXXXXXXX
XXXX  XXX

XXXX X XXXXXX XX XXXXXXXXXXXX XXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXXX XXXXXX XXXXXXXX XXXX XXX
    BB BBBBBB BB BBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
        
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
    XXXXXX
    BBBB
    BB BBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
        
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
    XXXXXX
    BBBBB
    BBBBB
    XXXX XXX XX XXXXXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXX
                    XXXX

                XXXXXX

                XXXX XXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXX
                    XXXXXXXXX
                XXXXXX
            XXXXXX
            XXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
            XXXX XXXX XXXXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
            BB BBBBBB BBB BBBBBBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            BBBB BBB BBBBBB BBB BBBBBBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            XXXX
            BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX

            BB BBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                        XXXX
                            XXX XXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXX XXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
                        XXXXX
                    XXXXXXXX

                    XXXXXXX
                        BBB BBBBBB BB BBBBBBBBBBBBB
                        BB BBBBBBBBBBBBB BB BBB BBB BBBBBBBBBBBBB B BBB
                        XXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXX XXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXX XXXXXX  XXXXX
                            XXX XXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXXXXX
                                        XXX
                                         FFFFXX
                                XXXXXXXXX
                            XXXXX
                            XXXX XXXXX
                            XXXX XXXXX
                            XXXX XXXXX
                        XXXXX
                        BBBB
                        XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXX XXXXXX  XXXXX
                            XXX XXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXXXXX
                                        XXX
                                         FFFFXX
                                XXXXXXXXX
                            XXXXX
                            XXXX XXXXX
                            XXXX XXXXX
                            XXXX XXXXX
                        XXXXX
                        BBBBB
                        BBBBBB
                    XXXXXXXX
                XXXXXXXX
            XXXXXX
            BBBBB
        XXXXXX
    XXXXXX

XXXXXX



XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXX XXXXXX XX XXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX XXX XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXX XX XXXX
                    XXXXXXXXXX XXXX XXX
                    XXXXXXXXXXXXX XXXXX XXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX
                    XXXXXXXX
                    XXXXXXXX
                    XXXXX XXXXXX XXXXXXXXXXX
                XXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBXX
                    BBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            BB BBBBBBB
                            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                BBB BBBBBB BB BBBBBBB
                                XXXXXXX XXXXXXXXXXXXXXXXXX
                                BBBBBB
                            XXXXXX
                            BBBBB
                        XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

BBBBBBBB