BBBBBBB BBBBBBBBBBB
BBBBB BBBBBXXXXX XXXXXBBBBBBBB
BBBBB BBBBBBB

XXXX XXX XXXXXXX XXXXXXX XXXXX XXXXXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXX X XXXXXXXXXXXXXXXXXXXXX
    XXXXXXX X XXXXXXXXXXXXXXXXXX
    XX XXXX XX XXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
    X
XXXXXXXXX
XXXX XXX XXXXXXX XXXXXXX XXXXX XXXXXXXXXX XXX

XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXX
        XXXXX
    XXXXXX
    XXXX

    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
        XX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXXX XXXXXX XXXX XX XXXXXXXXX XXXX XXXXXX XXXXXXXXX XXXXX XXXX 
            XXXXXXXXX XXXXXXXXXX XXXX XXXXXX XXX XXXXX XXXX XX XXXXXXXXX XXXXXXXX XXXX XX XXXX XXXXX XXXXXXXX XXXXX
            XXXX XXXX XXX XXX XXXXXX XXX XXXXXXXX 
            XXXX
            XXXX
            XXXXXXXX XXXXX XXXXXXXXXXXX XX XXXXX XXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX
        XXXX
    XXXXXX

    XXXX

    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXX
            BB BBBBBB BB BBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            BBBB
            BB BBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            BBBBB
            BBBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBXX
                BBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXX XXXXX XXXX XXXXXX
                        XXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX

            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX
            XXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXX
            BB BBBBBBBBBBBBB
            XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXX XXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            BBBBB
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBXX
                BBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXXX
            XXXXXXX

            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXX
                XXXXX
            XXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB
