BBBBBBB BBBBBBBBBBBBB
BBBBB BBBBB  BBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXX XXX XXX XXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXX XXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                BB BBBBBBBBBB BB BBBBBBBB BBBB
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX XXXXXX XX XXXXXXX XXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBB
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX XXXXX XXXXXXX XXXXXXXX XX XXXXXXX XXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXX XXXXX XXX XXX XXXXXXX XXX
            XX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
                BB BBBBBBBBBB B B
                 XXX XX 
                XXXX XXX XXXXXXXXXXX
            BBBBB
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXX XXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    BB BBBBBBBBBB B B
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                XXXX
                    BBB BBBBB BB BBBBBB
                    XXX XXXXXXXXXXXX  XXXXX
                    BBBBBB
                XXXXX
            XXXXXXXX

            XXXXXXX
                BB BBBBBBBBBBBB
                BBB BBBBBBBBBBB BB BBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                    XXX XXXXXXXXXXXX  XXXXX
                    XXXX  XXXXX
                    XXXX  XXXXX
                    XXXX  XXXXX
                    XXXX  XXXXX
                    XXX XXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXX
                                XXX
                                 FFFFXX
                        XXXXXXXXX
                    XXXXX
                XXXXX
                BBBBBB
                BBBB BBBBBBBBBB
                BBB BBBBBBBBB BB BBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                    XXX XXXXXXXXXXXX  XXXXX
                    XXXX  XXXXX
                    XXXX  XXXXX
                    XXXX  XXXXX
                    XXXX  XXXXX
                    XXXX  XXXXX
                    XXX XXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXX
                                XXX
                                 FFFFXX
                        XXXXXXXXX
                    XXXXX
                    XXXX
                        BB BBB BBBBBBBBBBBBBBBBBBBBB
                        XXXXXXX
                        BBBB
                        XXXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXX
                    XXXX
                        BB BBBBBBBBBBBBBBBBBBBBB BB BBBB
                        XXXX
                        BBBB
                        
                        BBBBB
                    XXXXX
                    XXX XXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXX
                                XXX
                                 FFFFXX
                        XXXXXXXXX
                    XXXXX
                XXXXX
                BBBBBB
                BBBBB
            XXXXXXXX
        XXXXXXXX
    XXXXXX
    BBBB

    XX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXX
        XXX XXXXX XXXX XXX XXXXXXXXXXXX XXX XXX XXX XXXXXXX XXXXXXX XXXXXX XXXXX XX XXXX XXXXXXXX
    XXXX
    BBBBB

XXXXXX

BBBBBBBB