BBBBBBB BBBBBBBBBBBBB
BBBBB BBBBB  BBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX

    XXXX XXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXX
                        
                    XXXX
                XXXXXX

                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX
                    BB BBBBBBBBBBBBBBBB

                    XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXXX
                    XXXXXXX
                    BBBB
                    XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXX
                    XXXXXXX
                    BBBBB
                XXXXXX
            XXXXXX

            XX XXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXX 
            XXXX

            XX XXXXXXXXX XXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBB
                XXXXXXX 
                BBBB
                XXXXXXX XXX XXX
                BBBBB
            XXXX

            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXX XX  FFFFXX
                        XXXXXXXXX
                    XXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXX XXX XX 
                             FFFFXX
                        XXXXXXXXX
                    XXXX
                    XXXX
                    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XX  FFFFXX
                        XXXXXXXXX
                    XXXXXXXX
                XXXXXX
                BB BBBBBBBBBBBB BB BBBBBB
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                BBBBB
            XXXXXX
        XXXXXX

        XXXX XXXX XX XXXX XXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXX
            BB BBBBBBBBBBBB
            XX XXXXXXXXX XXXXXXXXXXXXX
                XXXXX
                XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX

            XXXX XXXXXXXXXXXXXXXXXXX
                BBB BBBB BB BBBBBBBBBBBB
                XX XXXXXXBBB BBBBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX
                            
                        XXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                            XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                                BB BBBBBBBBBB
                                XXXXX
                                BBBB
                                XXXXXX
                                BBBBB
                            XXXXXXX
                        XXXXXX
                    XXXXXX
                XXXX
                BBBBBB
            XXXXXX

            BBBBB

        XXXXXX
    XXXXXX
XXXXXX

BBBBBBBB