BBBBBBB BBBBBBBBBBBBB
BBBBB BBBBB  BBBBBBBB

BBBBB BBBBBBB
XXXX X XXXXXX XX XXXXXXXXXXXX XXXXX XXX

XXXX XXX XXXXXXXXXX XXXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXX X XXXXXXXXXXXXXXXXXXXXX
    XXXXXX X XXXXXXXXXXXXXXXXXX
    XX XXXX XX XXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
    X
XXXXXXXXX
XXXX  XXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXX

    XXXX
    BB BBBBBBBBBBBBB

    XX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
        
    XXXX

    BBBB
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
            BB BBBBBB BB BBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            BBBB
            BB BBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            BBBBB
            BBBBB
        XXXXXX

        XXXX XXXXXXXXXXXXXX
            XXXX XXXXXXX XXXXXXX XXX
            BB BBBBBBBBBBBBBB
            XX XXXXXXXXX XXXXXXXXXXXXX XXXXXXX X XXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXX X XXXX

            XXXX

            BB BBBBBBBBBBBBB
            XX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XX  FFFFXX
                XXXXXXXXX
            XXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XX  FFFFXX
                XXXXXXXXX
            XXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXX  XXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXX
            XXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX X XXX XXXXX
            XXXXXXXXX
            BBBB
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXX X XXXXXXXX XXX XXXXXXXXX XXX XXXXXXXXX
                    XXXX
                XXXXXX

                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXX
                    XXXXXXXXX
                XXXXXX
            XXXXXX
            BBBBB
            XXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XX  FFFFXX
                        XXXXXXXXX
                    XXXX

                    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXX XX  FFFFXX
                        XXXXXXXXX
                    XXXXXXXX

                XXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX

            BBBB
            XX XXXXXXXXXXX XXXXXXX XXXX XXX XXXXXX XXXX
            XXXX XXXXX XXXX XXXX XXX XXX XXXXX XXXX XXXX XXX
            BBBBB
        XXXXXX

        XXXX XXXXXXXXXXXXXX
            XXXX XXXXX XXXXX XXXXXXX XXXXXXX XX XXXXXX XXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X XXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX X XXXX

        XXXXXX


    XXXXXX
    BBBBB
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXX XXXXXXX XXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX

XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX XXX XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXX
                    XXX XX XXXX
                    XXXXXXXXXX XXXX XXX
                    XXXXXXXXXXXXX XXXXX XXX XXXXXXXX XXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX
                    XXXXXXXX
                    XXXXXXXX
                    XXXXX XXXXXX XXXXXXXXXXX
                XXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXX
                    BBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

BBBBBBBB