BBBBBBB BBBBBBBBBBBBB
BBBBB BBBBB  BBBBBBBB

BBBBB BBBBBBB
XXXX X XXXXXX XX XXXXXXXXXXXX XXXXX XXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    BB BBBBBBB

    XX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
        
    XXXX

    BBBB

    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX
            BB BBBBBBBBBBBB
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXX
                        
                    XXXX
                XXXXXX

                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    BB BBBBBBBB
                    XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                        XXXXX
                    XXXXXXX
                    BBBB
                    XXXXX XXXXXXXXXXXX XXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXX
                
                XXXX
                    X  X
                XXXXX
            XXXX

            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XX  FFFFXX
                        XXXXXXXXX
                    XXXX
                    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXX XX  FFFFXX
                        XXXXXXXXX
                    XXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    BB BBBBBBBB
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBB
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                XXXXXX
            XXXXXX

            BBBB
            XXX XXXX XXXXXXXXXXX XXXXXXX
            BBBBB

        XXXXXX

        XXXX XXXX XXXXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXX
            BB BBBBBBBBBBBBB
            XX XXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXX
                XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX

            XXXX XXXXXXXXXXXXXXXXXXX
                BBB BBBBBBB BB BBBBBBBBBBBBB
                XX XXXXXXBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXX
                BBBBBB
            XXXXXX

            BBBBB

        XXXXXX

    XXXXXX

    XXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX

    XXXX XXXXXXXXXXXX

        XXXX XXXX XXXXXX XXX XXXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXX
            BB BBBBBBBBBBBB
            XX XXXXXXXXX XXXXXXXXXXXXX
                XXXXXX
                XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX

            XXXX XXXXXXXXXXXXXXXXXXX
                BB BBBBBB
                BBB BBBBB BB BBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXX
                BBBBBB
                BBBBB
            XXXXXX
            BBBBB
        XXXXXX

        XXXX XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXX
            BB BBBBBBBBBBBB
            XX XXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX
                XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX

            XXXX XXXXXXXXXXXXXXXXXXX
                BB BBBBBBB
                BBB BBBBBB BB BBBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXX
                BBBBBB
                BBBBB
            XXXXXX
            BBBBB
        XXXXXX

    XXXXXX
    BBBBB
XXXXXX
BBBBBBBB