# Generated by Django 2.2.4 on 2019-09-23 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerboseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_title', models.CharField(blank=True, max_length=30, null=True)),
                ('log_description', models.TextField(max_length=1000)),
                ('logged_on', models.DateTimeField(auto_now_add=True)),
                ('reference_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Projects')),
            ],
            options={
                'verbose_name_plural': 'VerboseLogs',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_name', models.CharField(max_length=50)),
                ('error_description', models.TextField(max_length=500)),
                ('point_of_origin', models.CharField(max_length=100)),
                ('logged_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('warning_level', models.IntegerField(default=0)),
                ('reference_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Projects')),
                ('resolved_by', models.ManyToManyField(related_name='resolver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ErrorLog',
                'ordering': ['logged_on'],
            },
        ),
    ]
