# Generated by Django 2.2.4 on 2019-09-24 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_logger', '0002_auto_20190924_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='resolved_by',
            field=models.ManyToManyField(blank=True, related_name='resolver', to=settings.AUTH_USER_MODEL),
        ),
    ]
