# Generated by Django 2.2.4 on 2019-09-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_logger', '0003_auto_20190924_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verboselog',
            name='log_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
