# Generated by Django 2.2.4 on 2019-09-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_logger', '0006_errorlog_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='verboselog',
            name='identifier',
            field=models.CharField(blank=True, default='Anonymous', max_length=50, null=True),
        ),
    ]
