# Generated by Django 2.2.4 on 2019-10-01 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('error_logger', '0008_auto_20190929_0713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorlog',
            options={'verbose_name_plural': 'errorLogs'},
        ),
    ]
