XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
BBBB BBBBBB

XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXX
        BBBBB BBBBBBBBBBBBB X XXXXXXXXXX
    XXXXXXXX
    XXXX XXXXXX XXXXXXXX XXX XXXXXXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XX


    XXXX XXXXXX XXXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXX XXXXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

    XXXX XXXXXX XX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXX XXXXXXXX XXXXXXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBXX XXXXXXXXX
XXXXXXX

XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    BBBBB BBBBBBBBBBBBBBB

XXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
    XXXX
    XXXX
    XXXX
    XX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XX XXXX XX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
XXXXXXXXX